deploy_path: /var/projects/tutorials
host: stackbuilders@www.stackbuilders.com
repo: git@stackbuilders-tutorials:stackbuilders/tutorials.git
revision: origin/production
build_script:
  - source config/production.env && stack setup && make rebuild
